### ISSUE TITLE
The problem with write_sd_card.yml

### ISSUE THREAD

**Issue by cyril-mamai** [gronke/raspberry-provisioning#2]
Good day!
I have the errors while running the write_sd_card.yml

Please see below. 

TASK: [custom module] ********************************************************\* 
fatal: [localhost] => Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/ansible/runner/**init**.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 1032, in _executor_internal_inner
    result = handler.run(conn, tmp, module_name, module_args, inject, complex_args)
  File "/home/mamai/raspberry-provisioning/action_plugins/confirm_device.py", line 95, in run
    self.print_disks()
  File "/home/mamai/raspberry-provisioning/action_plugins/confirm_device.py", line 75, in print_disks
    p = Popen(cmd, stdin=PIPE, stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

My installation is Ububtu
ansible 1.9.2
  configured module search path = /usr/share/my_modules/

**Comment by vladdoster** [comment]
lol
